services:
  db:
    container_name: moneykeep_db
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/pgsql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneykeep_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moneykeep_frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - static:/app/build

  gateway:
    container_name: moneykeep_proxy
    build: ./nginx
    ports:
      - "1111:80"
    volumes:
      - static:/moneykeep_static/
    depends_on:
      - backend

volumes:
  pg_data:
  static: