services:
  db:
    container_name: moneykeep-db
    image: postgres:17-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/pgsql/data

  backend:
    container_name: moneykeep-backend
    image: pave138/moneykeep_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    volumes:
      - media:/app/media

  gateway:
    container_name: moneykeep-proxy
    image: pave138/moneykeep_proxy
    restart: always
    ports:
      - "8088:80"
    volumes:
      - media:/media
    depends_on:
      - backend

volumes:
  pg_data:
  media:
